# Generated by Django 5.1.7 on 2025-03-27 00:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_alarm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='alarm_time',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='description',
        ),
        migrations.AddField(
            model_name='alarm',
            name='message',
            field=models.TextField(default='Night Pillow Alarm'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 27, 0, 0, 35, 212406, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='alarm',
            name='triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep_time', models.TimeField()),
                ('wake_up_time', models.TimeField()),
                ('sleep_duration', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
