# Generated by Django 5.1.7 on 2025-03-27 00:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0004_remove_alarm_alarm_time_remove_alarm_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 27, 0, 52, 19, 452621, tzinfo=datetime.timezone.utc)),
        ),
    ]
