# Generated by Django 5.1.7 on 2025-03-31 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0005_alarm_user_alter_alarm_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 31, 14, 59, 58, 329289, tzinfo=datetime.timezone.utc)),
        ),
    ]
