# Generated by Django 5.1.7 on 2025-03-31 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0007_alter_alarm_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 31, 16, 9, 52, 562911, tzinfo=datetime.timezone.utc)),
        ),
    ]
